# Generated by Django 5.1.4 on 2025-01-04 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('duration_days', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('rating', models.FloatField()),
                ('description', models.TextField()),
                ('image', models.FileField(upload_to='')),
                ('max_capacity', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('accommodation', models.BooleanField(default=False)),
                ('meals', models.BooleanField(default=False)),
                ('transport', models.BooleanField(default=False)),
            ],
        ),
    ]
